### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Facyla**
Added French translation file

### CODE REVIEW

**Comment by iionly** [comment]
@Facyla I've added the commit that wil contain the changes for the next releases of the Poll plugin (version 1.10.6 and 2.0.1 for Elgg 1.X and 2.X respectively). These changes also include some new and/or modified language strings. Would you like to update the French translations? If you would be able to update the French translations soon (let's say within a week or so) I could publish the next versions of the Poll plugin with the complete French translations.

**Comment by Facyla** [comment]
I am abroad and will not have the time to work on it this week, but i should be able to work on this next week if it's OK for you ?

**Comment by iionly** [comment]
That would be okay. I think it would be better to have the complete French translation included in the next release as I don't know how long it will be until another new release would become necessary.

**Comment by Facyla** [comment]
Done ! I've updated the translation (or added it) for the 3 branches

I had forked this plugin to a "survey" plugin which you might be interested in : https://github.com/Facyla/esope/tree/master/mod/survey (stable version is in branch master, version in branch 1.12 has not been fully updated to Elgg 1.12 yet)
This idea was to be able to set up multi-questions surveys, with different types of questions
It also uses a datavisualization plugin to show some results : https://github.com/Facyla/esope/tree/master/mod/elgg_dataviz
If you find them useful i'd be happy to get some feedback :)

**Comment by iionly** [comment]
Thanks for updating the translations. Though I will very likely not make another new release for Elgg 1.9 anymore at this time (there's not really a reason to stay on 1.9 as updating up to 1.12 shouldn't cause issues if your site works find on 1.9).

I might take a look at your survey plugin at some time (if only to look for inspiration). Though I'm afraid I can't say when I will have the time to do so.

**Pull request merged**
