### PR TITLE
Update widget.php

### PR DESCRIPTION
**Pull request by KitsuneSolar**

### CODE REVIEW

**Comment by iionly** [comment]
Could you explain why you think this change is necessary? It also seens to me that getting the text "Polls" displayed as fallback might not really makes sense. As the image is more or less only displayed for decorative purposes it might also work simply with alt="" instead if it would be really necessary to have the alt attribute included at all.

**Comment by KitsuneSolar** [comment]
By the standards of HTML ALT attribute is required. Why not add? :)

**Comment by iionly** [comment]
Strictly speaking you are right, the alt attribute is required. Though in this case the image is only meant as decoration. I think the alternative text "Polls" wouldn't really fit. I'm currently on holiday so I can't do much as of testing etc. right now. I'll look into it once back home.

**Comment by iionly** [comment]
Replaced and fixed by https://github.com/iionly/poll/commit/96aa22c5cbe5967658490884a26efc6739e2a76c.

**Pull request closed without merging**
